@startuml
'https://plantuml.com/class-diagram

interface GradeDAO{
+getAllGrades():List<Grade>
+doAdd(Grade grade):void
+doDelete(String playerName , String time):void
+findGrade(String playerName):List<Grade>

}

Class GradeDaoImpl {
- grades: List<Grade>
+getAllGrades():List<Grade>
+doAdd(Grade grade):void
+doDelete(String playerName , String time):void
+findGrade(String playerName):List<Grade>

}

Class Grade {
-playerName:String
-Time:String
-Score:int
+Grade(String playerName) , String time , int Score)
+getPlayerName():String
+getTime():String
+getScore():int
}

GradeDaoImpl ..|> GradeDAO
GradeDaoImpl --> Grade
@enduml