package edu.hitsz.application;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class ScoreUI {
    private JPanel mainPanel;
    private JLabel headerLabel;
    private JTable scoreTable;
    private JButton deleteButton;
    private JScrollPane tableScrollPanel;
    private JLabel easyButton;
    private DefaultTableModel model;

    // 构造函数开始
    public ScoreUI() {
        // 1. 初始化表格列名
        String[] columnName = {"名次", "玩家名", "得分", "记录时间"};

        // 2. 暂时使用测试数据
        String[][] tableData = {
                {"1", "test", "100", "04-11 10:11"},
                {"2", "player", "50", "04-12 11:22"}
        };

        // 3. 配置表格模型 (注意这里大括号的闭合)
        model = new DefaultTableModel(tableData, columnName) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false; // 设置单元格不可编辑
            }
        };

        // 这两句执行语句必须安安稳稳地呆在构造函数内部！
        scoreTable.setModel(model);
        tableScrollPanel.setViewportView(scoreTable);

        // 4. 删除按钮事件逻辑
        deleteButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int row = scoreTable.getSelectedRow();
                if (row != -1) {
                    int result = JOptionPane.showConfirmDialog(deleteButton, "是否确定删除?");
                    if (JOptionPane.YES_OPTION == result) {
                        model.removeRow(row);
                    }
                } else {
                    JOptionPane.showMessageDialog(mainPanel, "请先选择一条记录");
                }
            }
        });
    } // 构造函数结束

    // 弹窗输入姓名的方法
    public void showInputNameDialog(int score) {
        String playerName = JOptionPane.showInputDialog(mainPanel, "游戏结束，你的得分为 " + score + "。\n请输入玩家名字：");
        if (playerName != null && !playerName.trim().isEmpty()) {
            System.out.println("玩家: " + playerName + ", 得分: " + score);
        }
    }

    // 获取主面板的方法
    public JPanel getMainPanel() {
        return mainPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        easyButton = new JLabel();
        easyButton.setText("难度：EASY");
        panel1.add(easyButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panel1.add(spacer2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        tableScrollPanel = new JScrollPane();
        panel1.add(tableScrollPanel, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        scoreTable = new JTable();
        tableScrollPanel.setViewportView(scoreTable);
        deleteButton = new JButton();
        deleteButton.setText("删除选中记录");
        panel1.add(deleteButton, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}