package edu.hitsz.application;
import edu.hitsz.dao.Grade;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import edu.hitsz.dao.GradeDaoImpl;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

public class ScoreUI {
    private JPanel mainPanel;
    private JLabel headerLabel;
    private JTable scoreTable;
    private JButton deleteButton;
    private JScrollPane tableScrollPanel;
    private JLabel easyButton;
    private DefaultTableModel model;

    private GradeDaoImpl currentDao;

    // 构造函数开始
    public ScoreUI() {
        // 1. 初始化表格列名
        String[] columnName = {"名次", "玩家名", "得分", "记录时间"};

        model = new DefaultTableModel(null, columnName) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false; // 设置单元格不可编辑
            }
        };


        scoreTable.setModel(model);
        tableScrollPanel.setViewportView(scoreTable);

        // 获取表格的列模型
        javax.swing.table.TableColumnModel columnModel = scoreTable.getColumnModel();

        // 设置“名次”列宽度（较窄）
        columnModel.getColumn(0).setPreferredWidth(40);
        columnModel.getColumn(0).setMaxWidth(60);

        // 设置“玩家名”列宽度
        columnModel.getColumn(1).setPreferredWidth(100);

        // 设置“得分”列宽度
        columnModel.getColumn(2).setPreferredWidth(80);

        // 设置“记录时间”列宽度
        columnModel.getColumn(3).setPreferredWidth(200);
        columnModel.getColumn(3).setMinWidth(150); // 设置最小宽度，防止被挤压

        // 2.删除按钮事件逻辑
        deleteButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int row = scoreTable.getSelectedRow();
                if (row != -1) {
                    int result = JOptionPane.showConfirmDialog(deleteButton, "是否确定删除?");
                    if (JOptionPane.YES_OPTION == result) {
                        String playerName = (String) model.getValueAt(row,1);
                        String time = (String) model.getValueAt(row,3);
                        //调用  DAO 删除文件中的持久化数据
                        if (currentDao != null){
                            currentDao.doDelete(playerName,time);
                        }
                        model.removeRow(row);
                    }
                } else {
                    JOptionPane.showMessageDialog(mainPanel, "请先选择一条记录");
                }
            }
        });
    } // 构造函数结束

    public void loadScoreData(String filePath, int difficulty){
        this.currentDao = new GradeDaoImpl(filePath);
        // 2. 更改左上角难度提示 Label (你在 UI 里的变量名是 easyButton)
        String diffText = "EASY";
        if (difficulty == 2) diffText = "NORMAL";
        if (difficulty == 3) diffText = "HARD";
        easyButton.setText("当前难度：" + diffText);

        // 3. 利用 DAO 取出数据并按分数排序
        List<Grade> grades = currentDao.getAllGrades();
        grades.sort((g1, g2) -> Integer.compare(g2.getScore(), g1.getScore()));

        // 4. 清空旧数据
        model.setRowCount(0);

        // 5. 遍历填入新数据
        for (int i = 0; i < grades.size(); i++) {
            Grade g = grades.get(i);
            model.addRow(new Object[]{
                    i + 1,              // 名次
                    g.getPlayerName(),  // 玩家名
                    g.getScore(),       // 得分
                    g.getTime()         // 记录时间
            });
        }
    }

    // 弹窗输入姓名的方法
    public void showInputNameDialog(int score) {
        String playerName = JOptionPane.showInputDialog(mainPanel, "游戏结束，你的得分为 " + score + "。\n请输入玩家名字：");
        if (playerName != null && !playerName.trim().isEmpty()) {
            System.out.println("玩家: " + playerName + ", 得分: " + score);
        }
    }

    // 获取主面板的方法
    public JPanel getMainPanel() {
        return mainPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        easyButton = new JLabel();
        easyButton.setText("难度：EASY");
        panel1.add(easyButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panel1.add(spacer2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        tableScrollPanel = new JScrollPane();
        panel1.add(tableScrollPanel, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        scoreTable = new JTable();
        tableScrollPanel.setViewportView(scoreTable);
        deleteButton = new JButton();
        deleteButton.setText("删除选中记录");
        panel1.add(deleteButton, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}